name: Latest GoSecNinja Content
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with GoSecNinja Videos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "GS-YOUTUBE"
          readme_path: ./readme.md
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCcrWxBaxcYh7xsumEaya9Hw"
  update-readme-with-blog:
    name: Update this repo's README with GoSecNinja latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "GS-BLOG"
          readme_path: ./readme.md
          feed_list: "https://gosec.ninja/index.xml#feed"